name: candidate

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  copy_tag_and_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}

      - name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/shinofara/cicd:${{github.event.pull_request.head.sha}}
          dst: |
            ghcr.io/shinofara/cicd:latest

      - run: echo "gcloud run deploy dummy --project production --image=ghcr.io/shinofara/cicd:${{github.event.pull_request.head.sha}}"