name: feature

on:
  push:
    branches-ignore: ["main"]

jobs:
  lint:
    uses: ./.github/workflows/golangci-lint.yml
    with:
      event: feature
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test -shuffle on -race
  build_and_push:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}

      - name: Build and push and cache
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shinofara/cicd:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      # Cacheを保存
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
