name: daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  contents: read

jobs:
  vulns:
    uses: ./.github/workflows/reusable-vulns.yml
  lint:
    uses: ./.github/workflows/reusable-golangci-lint.yml
    with:
      event: daily
