name: production

on:
  release:
    types: [published]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: check target branch
        if: github.event.release.target_commitish != 'main'
        run: |
          echo "github.event.release.target_commitish want main, got ${{github.event.release.target_commitish}}"
          exit 1

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u ${OWNER,,} --password-stdin
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}

      - name:
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/shinofara/cicd:latest
          dst: |
            ghcr.io/shinofara/cicd:${{ env.TAG }}

      - run: echo "gcloud run deploy dummy --project production --image=ghcr.io/shinofara/cicd:${{ env.TAG }}"